apiVersion: apps/v1
kind: Deployment
metadata:
  name: codedabbler
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: codedabbler
  template:
    metadata:
      labels:
        app: codedabbler
    spec:
      containers:
      - image: localhost:5000/codedabbler
        name: codedabbler
        ports:
        - containerPort: 80